<?php

namespace MovieBundle\Repository;

use Doctrine\ORM\EntityRepository;
use MovieBundle\Entity\Actor;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{
    /**
     * @param Actor $actor
     * @return array
     */
    public function findMoviesByActor(Actor $actor)
    {
        $queryBuilder = $this->createQueryBuilder('movie');
        $queryBuilder->addSelect('actor')
            ->join('movie.actors', 'actor')
            ->where('actor = :actor')
            ->setParameter('actor', $actor);

        return $queryBuilder->getQuery()->getResult();
    }
}
