<?php

namespace MovieBundle\Repository;

use Doctrine\ORM\EntityRepository;
use MovieBundle\Entity\Movie;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends EntityRepository
{
    /**
     * @param Movie $movie
     * @return mixed
     */
    public function findAverageRatingByMovie(Movie $movie)
    {
        $dql = "SELECT AVG(rating.rating) FROM MovieBundle:Rating rating WHERE rating.movie = :movie";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameter('movie', $movie);

        return $query->getSingleScalarResult();
    }
}
